name: react
version: 5.0.0
author: Clean Team <clean@vacuumlabs.com>
description: Bindings of the ReactJS library for building interactive interfaces.
homepage: http://cleandart.github.io/react-dart/
environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'
dependencies:
  js: ^0.6.0
dev_dependencies:
  test: ^0.12.32+1
